# fly.toml app configuration file generated for datingappsp on 2024-03-14T15:06:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingappsp'
primary_region = 'otp'

[build]
  image = 'silvianp/datingapp:latest'

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "292961516881324"
  CloudinarySettings__CloudName = "dsg7x1vg0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
