# fly.toml app configuration file generated for datingappinitproj-polished-thunder-2790 on 2024-03-14T11:16:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingappinitproj-polished-thunder-2790'
primary_region = 'otp'

[build]
  image = 'silvianp/datingapp:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dsg7x1vg0"
  CloudinarySettings__ApiKey="292961516881324"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
